# Generated by martinx/handrail's release workflow. Do not edit by hand.
class Handrail < Formula
  desc "Policy packs for coding agents: enforced where the agent allows it"
  homepage "https://handrail.bitey.ai"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/martinx/handrail/releases/download/v0.1.1/handrail-aarch64-apple-darwin.tar.gz"
      sha256 "18b47aca5ee9ccfefca9340a47694d8af83fc91536266cf812a24c44beffb534"
    end
    on_intel do
      url "https://github.com/martinx/handrail/releases/download/v0.1.1/handrail-x86_64-apple-darwin.tar.gz"
      sha256 "66c57db1e83173bef131c1dc672bd127aff60b1643185c0c5a8ca112c4189947"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/martinx/handrail/releases/download/v0.1.1/handrail-aarch64-unknown-linux-musl.tar.gz"
      sha256 "7787a4abaf1bb29bb129298e027814c2bbd58c25a1c842044dc40df70f48ffe0"
    end
    on_intel do
      url "https://github.com/martinx/handrail/releases/download/v0.1.1/handrail-x86_64-unknown-linux-musl.tar.gz"
      sha256 "1729538f9ca5ee28b1514d12053451c328fec5a1e08618d64cd6bb7c1d2e479a"
    end
  end

  def install
    bin.install "handrail"
  end

  def caveats
    <<~EOS
      Handrail runs itself through sudo to change enforced policy. The Homebrew prefix is
      writable by your user, so anything running as you could replace the binary before
      sudo runs it. For enforced policy, the install script (which installs to the
      root-owned /usr/local/bin) is the safer choice:
        curl -fsSL https://handrail.bitey.ai/install.sh | sh
      Run `handrail doctor` to check.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/handrail --version")
  end
end
